Repository lion-packages/authentication, pull requests merged in 2025-03, with the labels that each got.

#13 Updated Github Actions settings
  .github/workflows/php.yml
Labels: continuous integration

#14 Added dependency-review in Github Actions
  .github/workflows/php.yml
Labels: continuous integration

#12 Update PHPUnit v12
  composer.json
  composer.lock
  phpunit.xml
Labels: dependencies

#16 Added dependabot
  .github/dependabot.yml
  .github/workflows/php.yml
Labels: continuous integration

#18 PHPLint is integrated
  .github/workflows/php.yml
  .gitignore
  composer.json
Labels: dependencies, continuous integration

#19 The infection is added to Github Actions
  .github/workflows/php.yml
  src/LionAuthentication/Auth2FA.php
  tests/Auth2FATest.php
  tests/Providers/Auth2FAProviderTrait.php
  tests/Providers/Constants.php
Labels: continuous integration

#20 Update README.md
  .github/README.md
Labels: documentation
